version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=Qa5180_Identity
      - Qa5180_DB=Qa5180_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
